-- =====================================================================
-- V1 · Esquema inicial de la API de portería
-- Las decisiones detrás de cada columna están en docs/decisiones-fase0.md
--
-- REGLA: una vez fusionada en develop, esta migración NO se edita.
-- Cualquier cambio va en una migración nueva: V<yyyyMMdd_HHmm>__descripcion.sql
-- =====================================================================


-- ---------------------------------------------------------------------
-- auth (Dev B)
-- ---------------------------------------------------------------------
CREATE TABLE usuario (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(50)  NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,                -- BCrypt
    nombre         VARCHAR(120) NOT NULL,
    rol            VARCHAR(20)  NOT NULL,
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en      TIMESTAMP    NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT ck_usuario_rol CHECK (rol IN ('ADMIN', 'PORTERO'))
);


-- ---------------------------------------------------------------------
-- persona (Dev B)
-- ---------------------------------------------------------------------
CREATE TABLE persona (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(20)  NOT NULL,
    dni             VARCHAR(15)  NOT NULL,                -- también sirve como credencial (método DNI)
    nombres         VARCHAR(100) NOT NULL,
    apellidos       VARCHAR(100) NOT NULL,
    codigo          VARCHAR(20),                          -- código de alumno o empleado; visitantes no tienen
    area            VARCHAR(100),                         -- carrera o área de trabajo
    foto_url        VARCHAR(255),
    vigencia_inicio DATE         NOT NULL DEFAULT CURRENT_DATE,
    vigencia_fin    DATE,                                 -- NULL = sin vencimiento
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,   -- borrado lógico
    creado_en       TIMESTAMP    NOT NULL DEFAULT now(),
    actualizado_en  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_persona_dni UNIQUE (dni),
    CONSTRAINT uq_persona_codigo UNIQUE (codigo),
    CONSTRAINT ck_persona_tipo CHECK (tipo IN ('ESTUDIANTE', 'DOCENTE', 'PERSONAL', 'VISITANTE')),
    CONSTRAINT ck_persona_vigencia CHECK (vigencia_fin IS NULL OR vigencia_fin >= vigencia_inicio)
);

CREATE TABLE credencial (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id BIGINT       NOT NULL CONSTRAINT fk_credencial_persona REFERENCES persona (id),
    tipo       VARCHAR(10)  NOT NULL,
    valor      VARCHAR(100) NOT NULL,                     -- NFC: UID en hex mayúsculas sin separadores
    activa     BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT ck_credencial_tipo CHECK (tipo IN ('NFC', 'QR'))
);

-- Un sticker o QR solo puede estar ACTIVO en una persona a la vez.
-- Uno desactivado sí puede reasignarse a otra persona.
CREATE UNIQUE INDEX uq_credencial_activa ON credencial (tipo, valor) WHERE activa;
CREATE INDEX ix_credencial_persona ON credencial (persona_id);


-- ---------------------------------------------------------------------
-- dispositivo (Dev A)
-- ---------------------------------------------------------------------
CREATE TABLE dispositivo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    punto       VARCHAR(20)  NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL,                    -- SHA-256 en hex; el token en claro nunca se guarda
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    ultimo_ping TIMESTAMP,
    creado_en   TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_dispositivo_token UNIQUE (token_hash),
    CONSTRAINT ck_dispositivo_punto CHECK (punto IN ('PEATONAL', 'VEHICULAR'))
);


-- ---------------------------------------------------------------------
-- acceso (Dev A)
-- ---------------------------------------------------------------------
-- Una regla define CUÁNDO puede ENTRAR un tipo de persona por un punto.
-- Sin reglas activas para ese tipo y punto, no hay restricción horaria.
-- Un horario que cruza la medianoche se registra como dos reglas.
CREATE TABLE regla_acceso (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_persona VARCHAR(20)  NOT NULL,
    punto        VARCHAR(20),                             -- NULL = todos los puntos
    dias         VARCHAR(13)  NOT NULL,                   -- días ISO separados por coma: 1=lunes … 7=domingo
    hora_inicio  TIME         NOT NULL,
    hora_fin     TIME         NOT NULL,
    descripcion  VARCHAR(150),
    activa       BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en    TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT ck_regla_tipo_persona CHECK (tipo_persona IN ('ESTUDIANTE', 'DOCENTE', 'PERSONAL', 'VISITANTE')),
    CONSTRAINT ck_regla_punto CHECK (punto IN ('PEATONAL', 'VEHICULAR')),
    CONSTRAINT ck_regla_dias CHECK (dias ~ '^[1-7](,[1-7]){0,6}$'),
    CONSTRAINT ck_regla_horas CHECK (hora_fin > hora_inicio)
);

CREATE TABLE registro_acceso (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora     TIMESTAMP    NOT NULL,
    dispositivo_id BIGINT       NOT NULL CONSTRAINT fk_registro_dispositivo REFERENCES dispositivo (id),
    persona_id     BIGINT       CONSTRAINT fk_registro_persona REFERENCES persona (id),   -- NULL si nadie tiene esa credencial
    credencial_id  BIGINT       CONSTRAINT fk_registro_credencial REFERENCES credencial (id) ON DELETE SET NULL,
    metodo         VARCHAR(10)  NOT NULL,
    valor_leido    VARCHAR(100) NOT NULL,                 -- se guarda siempre, aunque la credencial luego se elimine
    direccion      VARCHAR(10)  NOT NULL,
    resultado      VARCHAR(20)  NOT NULL,
    CONSTRAINT ck_registro_metodo CHECK (metodo IN ('NFC', 'QR', 'DNI')),
    CONSTRAINT ck_registro_direccion CHECK (direccion IN ('ENTRADA', 'SALIDA')),
    CONSTRAINT ck_registro_resultado CHECK (resultado IN
        ('AUTORIZADO', 'NO_AUTORIZADO', 'INACTIVO', 'VENCIDO', 'FUERA_DE_HORARIO'))
);

CREATE INDEX ix_registro_fecha ON registro_acceso (fecha_hora DESC);
CREATE INDEX ix_registro_persona_fecha ON registro_acceso (persona_id, fecha_hora DESC);
-- Filtro de lectura duplicada: misma credencial en el mismo dispositivo en los últimos segundos.
CREATE INDEX ix_registro_duplicado ON registro_acceso (dispositivo_id, metodo, valor_leido, fecha_hora DESC);
